const languages = [
  {
    name: 'Abkhazian',
    native: 'аҧсуа бызшәа, аҧсшәа',
    code2l: 'ab',
    code3l: 'abk',
  },
  {
    name: 'Afar',
    native: 'Afaraf',
    code2l: 'aa',
    code3l: 'aar',
  },
  {
    name: 'Afrikaans',
    native: 'Afrikaans',
    code2l: 'af',
    code3l: 'afr',
  },
  {
    name: 'Akan',
    native: 'Akan',
    code2l: 'ak',
    code3l: 'aka',
  },
  {
    name: 'Albanian',
    native: 'Shqip',
    code2l: 'sq',
    code3l: 'sqi',
  },
  {
    name: 'Amharic',
    native: 'አማርኛ',
    code2l: 'am',
    code3l: 'amh',
  },
  {
    name: 'Arabic',
    native: 'العربية',
    code2l: 'ar',
    code3l: 'ara',
  },
  {
    name: 'Aragonese',
    native: 'aragonés',
    code2l: 'an',
    code3l: 'arg',
  },
  {
    name: 'Armenian',
    native: 'Հայերեն',
    code2l: 'hy',
    code3l: 'hye',
  },
  {
    name: 'Assamese',
    native: 'অসমীয়া',
    code2l: 'as',
    code3l: 'asm',
  },
  {
    name: 'Avaric',
    native: 'авар мацӀ, магӀарул мацӀ',
    code2l: 'av',
    code3l: 'ava',
  },
  {
    name: 'Avestan',
    native: 'avesta',
    code2l: 'ae',
    code3l: 'ave',
  },
  {
    name: 'Aymara',
    native: 'aymar aru',
    code2l: 'ay',
    code3l: 'aym',
  },
  {
    name: 'Azerbaijani',
    native: 'azərbaycan dili',
    code2l: 'az',
    code3l: 'aze',
  },
  {
    name: 'Bambara',
    native: 'bamanankan',
    code2l: 'bm',
    code3l: 'bam',
  },
  {
    name: 'Bashkir',
    native: 'башҡорт теле',
    code2l: 'ba',
    code3l: 'bak',
  },
  {
    name: 'Basque',
    native: 'euskara, euskera',
    code2l: 'eu',
    code3l: 'eus',
  },
  {
    name: 'Belarusian',
    native: 'беларуская мова',
    code2l: 'be',
    code3l: 'bel',
  },
  {
    name: 'Bengali',
    native: 'বাংলা',
    code2l: 'bn',
    code3l: 'ben',
  },
  {
    name: 'Bihari languages',
    native: 'भोजपुरी',
    code2l: 'bh',
    code3l: 'bih',
  },
  {
    name: 'Bislama',
    native: 'Bislama',
    code2l: 'bi',
    code3l: 'bis',
  },
  {
    name: 'Bosnian',
    native: 'bosanski jezik',
    code2l: 'bs',
    code3l: 'bos',
  },
  {
    name: 'Breton',
    native: 'brezhoneg',
    code2l: 'br',
    code3l: 'bre',
  },
  {
    name: 'Bulgarian',
    native: 'български език',
    code2l: 'bg',
    code3l: 'bul',
  },
  {
    name: 'Burmese',
    native: 'ဗမာစာ',
    code2l: 'my',
    code3l: 'mya',
  },
  {
    name: 'Catalan, Valencian',
    native: 'català, valencià',
    code2l: 'ca',
    code3l: 'cat',
  },
  {
    name: 'Chamorro',
    native: 'Chamoru',
    code2l: 'ch',
    code3l: 'cha',
  },
  {
    name: 'Chechen',
    native: 'нохчийн мотт',
    code2l: 'ce',
    code3l: 'che',
  },
  {
    name: 'Chichewa, Chewa, Nyanja',
    native: 'chiCheŵa, chinyanja',
    code2l: 'ny',
    code3l: 'nya',
  },
  {
    name: 'Chinese',
    native: '中文 (Zhōngwén), 汉语, 漢語',
    code2l: 'zh',
    code3l: 'zho',
  },
  {
    name: 'Chuvash',
    native: 'чӑваш чӗлхи',
    code2l: 'cv',
    code3l: 'chv',
  },
  {
    name: 'Cornish',
    native: 'Kernewek',
    code2l: 'kw',
    code3l: 'cor',
  },
  {
    name: 'Corsican',
    native: 'corsu, lingua corsa',
    code2l: 'co',
    code3l: 'cos',
  },
  {
    name: 'Cree',
    native: 'ᓀᐦᐃᔭᐍᐏᐣ',
    code2l: 'cr',
    code3l: 'cre',
  },
  {
    name: 'Croatian',
    native: 'hrvatski jezik',
    code2l: 'hr',
    code3l: 'hrv',
  },
  {
    name: 'Czech',
    native: 'čeština, český jazyk',
    code2l: 'cs',
    code3l: 'ces',
  },
  {
    name: 'Danish',
    native: 'dansk',
    code2l: 'da',
    code3l: 'dan',
  },
  {
    name: 'Divehi, Dhivehi, Maldivian',
    native: 'ދިވެހި',
    code2l: 'dv',
    code3l: 'div',
  },
  {
    name: 'Dutch, Flemish',
    native: 'Nederlands, Vlaams',
    code2l: 'nl',
    code3l: 'nld',
  },
  {
    name: 'Dzongkha',
    native: 'རྫོང་ཁ',
    code2l: 'dz',
    code3l: 'dzo',
  },
  {
    name: 'English',
    native: 'English',
    code2l: 'en',
    code3l: 'eng',
  },
  {
    name: 'Esperanto',
    native: 'Esperanto',
    code2l: 'eo',
    code3l: 'epo',
  },
  {
    name: 'Estonian',
    native: 'eesti, eesti keel',
    code2l: 'et',
    code3l: 'est',
  },
  {
    name: 'Ewe',
    native: 'Eʋegbe',
    code2l: 'ee',
    code3l: 'ewe',
  },
  {
    name: 'Faroese',
    native: 'føroyskt',
    code2l: 'fo',
    code3l: 'fao',
  },
  {
    name: 'Fijian',
    native: 'vosa Vakaviti',
    code2l: 'fj',
    code3l: 'fij',
  },
  {
    name: 'Finnish',
    native: 'suomi, suomen kieli',
    code2l: 'fi',
    code3l: 'fin',
  },
  {
    name: 'French',
    native: 'français, langue française',
    code2l: 'fr',
    code3l: 'fra',
  },
  {
    name: 'Fulah',
    native: 'Fulfulde, Pulaar, Pular',
    code2l: 'ff',
    code3l: 'ful',
  },
  {
    name: 'Galician',
    native: 'Galego',
    code2l: 'gl',
    code3l: 'glg',
  },
  {
    name: 'Georgian',
    native: 'ქართული',
    code2l: 'ka',
    code3l: 'kat',
  },
  {
    name: 'German',
    native: 'Deutsch',
    code2l: 'de',
    code3l: 'deu',
  },
  {
    name: 'Greek, Modern (1453–)',
    native: 'ελληνικά',
    code2l: 'el',
    code3l: 'ell',
  },
  {
    name: 'Guarani',
    native: "Avañe'ẽ",
    code2l: 'gn',
    code3l: 'grn',
  },
  {
    name: 'Gujarati',
    native: 'ગુજરાતી',
    code2l: 'gu',
    code3l: 'guj',
  },
  {
    name: 'Haitian, Haitian Creole',
    native: 'Kreyòl ayisyen',
    code2l: 'ht',
    code3l: 'hat',
  },
  {
    name: 'Hausa',
    native: '(Hausa) هَوُسَ',
    code2l: 'ha',
    code3l: 'hau',
  },
  {
    name: 'Hebrew',
    native: 'עברית',
    code2l: 'he',
    code3l: 'heb',
  },
  {
    name: 'Herero',
    native: 'Otjiherero',
    code2l: 'hz',
    code3l: 'her',
  },
  {
    name: 'Hindi',
    native: 'हिन्दी, हिंदी',
    code2l: 'hi',
    code3l: 'hin',
  },
  {
    name: 'Hiri Motu',
    native: 'Hiri Motu',
    code2l: 'ho',
    code3l: 'hmo',
  },
  {
    name: 'Hungarian',
    native: 'magyarul',
    code2l: 'hu',
    code3l: 'hun',
  },
  {
    name: 'Interlingua (International Auxiliary Language Association)',
    native: 'Interlingua',
    code2l: 'ia',
    code3l: 'ina',
  },
  {
    name: 'Indonesian',
    native: 'Bahasa Indonesia',
    code2l: 'id',
    code3l: 'ind',
  },
  {
    name: 'Interlingue, Occidental',
    native: '(originally:) Occidental, (after WWII:) Interlingue',
    code2l: 'ie',
    code3l: 'ile',
  },
  {
    name: 'Irish',
    native: 'Gaeilge',
    code2l: 'ga',
    code3l: 'gle',
  },
  {
    name: 'Igbo',
    native: 'Asụsụ Igbo',
    code2l: 'ig',
    code3l: 'ibo',
  },
  {
    name: 'Inupiaq',
    native: 'Iñupiaq, Iñupiatun',
    code2l: 'ik',
    code3l: 'ipk',
  },
  {
    name: 'Ido',
    native: 'Ido',
    code2l: 'io',
    code3l: 'ido',
  },
  {
    name: 'Icelandic',
    native: 'Íslenska',
    code2l: 'is',
    code3l: 'isl',
  },
  {
    name: 'Italian',
    native: 'Italiano',
    code2l: 'it',
    code3l: 'ita',
  },
  {
    name: 'Inuktitut',
    native: 'ᐃᓄᒃᑎᑐᑦ',
    code2l: 'iu',
    code3l: 'iku',
  },
  {
    name: 'Japanese',
    native: '日本語 (にほんご)',
    code2l: 'ja',
    code3l: 'jpn',
  },
  {
    name: 'Javanese',
    native: 'ꦧꦱꦗꦮ, Basa Jawa',
    code2l: 'jv',
    code3l: 'jav',
  },
  {
    name: 'Kalaallisut, Greenlandic',
    native: 'kalaallisut, kalaallit oqaasii',
    code2l: 'kl',
    code3l: 'kal',
  },
  {
    name: 'Kannada',
    native: 'ಕನ್ನಡ',
    code2l: 'kn',
    code3l: 'kan',
  },
  {
    name: 'Kanuri',
    native: 'Kanuri',
    code2l: 'kr',
    code3l: 'kau',
  },
  {
    name: 'Kashmiri',
    native: 'कश्मीरी, كشميري‎',
    code2l: 'ks',
    code3l: 'kas',
  },
  {
    name: 'Kazakh',
    native: 'қазақ тілі',
    code2l: 'kk',
    code3l: 'kaz',
  },
  {
    name: 'Central Khmer',
    native: 'ខ្មែរ, ខេមរភាសា, ភាសាខ្មែរ',
    code2l: 'km',
    code3l: 'khm',
  },
  {
    name: 'Kikuyu, Gikuyu',
    native: 'Gĩkũyũ',
    code2l: 'ki',
    code3l: 'kik',
  },
  {
    name: 'Kinyarwanda',
    native: 'Ikinyarwanda',
    code2l: 'rw',
    code3l: 'kin',
  },
  {
    name: 'Kirghiz, Kyrgyz',
    native: 'Кыргызча, Кыргыз тили',
    code2l: 'ky',
    code3l: 'kir',
  },
  {
    name: 'Komi',
    native: 'коми кыв',
    code2l: 'kv',
    code3l: 'kom',
  },
  {
    name: 'Kongo',
    native: 'Kikongo',
    code2l: 'kg',
    code3l: 'kon',
  },
  {
    name: 'Korean',
    native: '한국어',
    code2l: 'ko',
    code3l: 'kor',
  },
  {
    name: 'Kurdish',
    native: 'Kurdî, کوردی‎',
    code2l: 'ku',
    code3l: 'kur',
  },
  {
    name: 'Kuanyama, Kwanyama',
    native: 'Kuanyama',
    code2l: 'kj',
    code3l: 'kua',
  },
  {
    name: 'Latin',
    native: 'latine, lingua latina',
    code2l: 'la',
    code3l: 'lat',
  },
  {
    name: 'Luxembourgish, Letzeburgesch',
    native: 'Lëtzebuergesch',
    code2l: 'lb',
    code3l: 'ltz',
  },
  {
    name: 'Ganda',
    native: 'Luganda',
    code2l: 'lg',
    code3l: 'lug',
  },
  {
    name: 'Limburgan, Limburger, Limburgish',
    native: 'Limburgs',
    code2l: 'li',
    code3l: 'lim',
  },
  {
    name: 'Lingala',
    native: 'Lingála',
    code2l: 'ln',
    code3l: 'lin',
  },
  {
    name: 'Lao',
    native: 'ພາສາລາວ',
    code2l: 'lo',
    code3l: 'lao',
  },
  {
    name: 'Lithuanian',
    native: 'lietuvių kalba',
    code2l: 'lt',
    code3l: 'lit',
  },
  {
    name: 'Luba-Katanga',
    native: 'Kiluba',
    code2l: 'lu',
    code3l: 'lub',
  },
  {
    name: 'Latvian',
    native: 'latviešu valoda',
    code2l: 'lv',
    code3l: 'lav',
  },
  {
    name: 'Manx',
    native: 'Gaelg, Gailck',
    code2l: 'gv',
    code3l: 'glv',
  },
  {
    name: 'Macedonian',
    native: 'македонски јазик',
    code2l: 'mk',
    code3l: 'mkd',
  },
  {
    name: 'Malagasy',
    native: 'fiteny malagasy',
    code2l: 'mg',
    code3l: 'mlg',
  },
  {
    name: 'Malay',
    native: 'Bahasa Melayu, بهاس ملايو‎',
    code2l: 'ms',
    code3l: 'msa',
  },
  {
    name: 'Malayalam',
    native: 'മലയാളം',
    code2l: 'ml',
    code3l: 'mal',
  },
  {
    name: 'Maltese',
    native: 'Malti',
    code2l: 'mt',
    code3l: 'mlt',
  },
  {
    name: 'Maori',
    native: 'te reo Māori',
    code2l: 'mi',
    code3l: 'mri',
  },
  {
    name: 'Marathi',
    native: 'मराठी',
    code2l: 'mr',
    code3l: 'mar',
  },
  {
    name: 'Marshallese',
    native: 'Kajin M̧ajeļ',
    code2l: 'mh',
    code3l: 'mah',
  },
  {
    name: 'Mongolian',
    native: 'Монгол хэл',
    code2l: 'mn',
    code3l: 'mon',
  },
  {
    name: 'Nauru',
    native: 'Dorerin Naoero',
    code2l: 'na',
    code3l: 'nau',
  },
  {
    name: 'Navajo, Navaho',
    native: 'Diné bizaad',
    code2l: 'nv',
    code3l: 'nav',
  },
  {
    name: 'North Ndebele',
    native: 'isiNdebele',
    code2l: 'nd',
    code3l: 'nde',
  },
  {
    name: 'Nepali',
    native: 'नेपाली',
    code2l: 'ne',
    code3l: 'nep',
  },
  {
    name: 'Ndonga',
    native: 'Owambo',
    code2l: 'ng',
    code3l: 'ndo',
  },
  {
    name: 'Norwegian Bokmål',
    native: 'Norsk Bokmål',
    code2l: 'nb',
    code3l: 'nob',
  },
  {
    name: 'Norwegian Nynorsk',
    native: 'Norsk Nynorsk',
    code2l: 'nn',
    code3l: 'nno',
  },
  {
    name: 'Norwegian',
    native: 'Norsk',
    code2l: 'no',
    code3l: 'nor',
  },
  {
    name: 'Sichuan Yi, Nuosu',
    native: 'ꆈꌠ꒿ Nuosuhxop',
    code2l: 'ii',
    code3l: 'iii',
  },
  {
    name: 'South Ndebele',
    native: 'isiNdebele',
    code2l: 'nr',
    code3l: 'nbl',
  },
  {
    name: 'Occitan',
    native: "occitan, lenga d'òc",
    code2l: 'oc',
    code3l: 'oci',
  },
  {
    name: 'Ojibwa',
    native: 'ᐊᓂᔑᓈᐯᒧᐎᓐ',
    code2l: 'oj',
    code3l: 'oji',
  },
  {
    name:
      'Church Slavic, Old Slavonic, Church Slavonic, Old Bulgarian, Old Church Slavonic',
    native: 'ѩзыкъ словѣньскъ',
    code2l: 'cu',
    code3l: 'chu',
  },
  {
    name: 'Oromo',
    native: 'Afaan Oromoo',
    code2l: 'om',
    code3l: 'orm',
  },
  {
    name: 'Oriya',
    native: 'ଓଡ଼ିଆ',
    code2l: 'or',
    code3l: 'ori',
  },
  {
    name: 'Ossetian, Ossetic',
    native: 'ирон æвзаг',
    code2l: 'os',
    code3l: 'oss',
  },
  {
    name: 'Punjabi, Panjabi',
    native: 'ਪੰਜਾਬੀ, پنجابی‎',
    code2l: 'pa',
    code3l: 'pan',
  },
  {
    name: 'Pali',
    native: 'पालि, पाळि',
    code2l: 'pi',
    code3l: 'pli',
  },
  {
    name: 'Persian',
    native: 'فارسی',
    code2l: 'fa',
    code3l: 'fas',
  },
  {
    name: 'Polish',
    native: 'język polski, polszczyzna',
    code2l: 'pl',
    code3l: 'pol',
  },
  {
    name: 'Pashto, Pushto',
    native: 'پښتو',
    code2l: 'ps',
    code3l: 'pus',
  },
  {
    name: 'Portuguese',
    native: 'Português',
    code2l: 'pt',
    code3l: 'por',
  },
  {
    name: 'Quechua',
    native: 'Runa Simi, Kichwa',
    code2l: 'qu',
    code3l: 'que',
  },
  {
    name: 'Romansh',
    native: 'Rumantsch Grischun',
    code2l: 'rm',
    code3l: 'roh',
  },
  {
    name: 'Rundi',
    native: 'Ikirundi',
    code2l: 'rn',
    code3l: 'run',
  },
  {
    name: 'Romanian, Moldavian, Moldovan',
    native: 'Română',
    code2l: 'ro',
    code3l: 'ron',
  },
  {
    name: 'Russian',
    native: 'русский',
    code2l: 'ru',
    code3l: 'rus',
  },
  {
    name: 'Sanskrit',
    native: 'संस्कृतम्',
    code2l: 'sa',
    code3l: 'san',
  },
  {
    name: 'Sardinian',
    native: 'sardu',
    code2l: 'sc',
    code3l: 'srd',
  },
  {
    name: 'Sindhi',
    native: 'सिन्धी, سنڌي، سندھی‎',
    code2l: 'sd',
    code3l: 'snd',
  },
  {
    name: 'Northern Sami',
    native: 'Davvisámegiella',
    code2l: 'se',
    code3l: 'sme',
  },
  {
    name: 'Samoan',
    native: "gagana fa'a Samoa",
    code2l: 'sm',
    code3l: 'smo',
  },
  {
    name: 'Sango',
    native: 'yângâ tî sängö',
    code2l: 'sg',
    code3l: 'sag',
  },
  {
    name: 'Serbian',
    native: 'српски језик',
    code2l: 'sr',
    code3l: 'srp',
  },
  {
    name: 'Gaelic, Scottish Gaelic',
    native: 'Gàidhlig',
    code2l: 'gd',
    code3l: 'gla',
  },
  {
    name: 'Shona',
    native: 'chiShona',
    code2l: 'sn',
    code3l: 'sna',
  },
  {
    name: 'Sinhala, Sinhalese',
    native: 'සිංහල',
    code2l: 'si',
    code3l: 'sin',
  },
  {
    name: 'Slovak',
    native: 'Slovenčina, Slovenský Jazyk',
    code2l: 'sk',
    code3l: 'slk',
  },
  {
    name: 'Slovenian',
    native: 'Slovenski Jezik, Slovenščina',
    code2l: 'sl',
    code3l: 'slv',
  },
  {
    name: 'Somali',
    native: 'Soomaaliga, af Soomaali',
    code2l: 'so',
    code3l: 'som',
  },
  {
    name: 'Southern Sotho',
    native: 'Sesotho',
    code2l: 'st',
    code3l: 'sot',
  },
  {
    name: 'Spanish, Castilian',
    native: 'Español',
    code2l: 'es',
    code3l: 'spa',
  },
  {
    name: 'Sundanese',
    native: 'Basa Sunda',
    code2l: 'su',
    code3l: 'sun',
  },
  {
    name: 'Swahili',
    native: 'Kiswahili',
    code2l: 'sw',
    code3l: 'swa',
  },
  {
    name: 'Swati',
    native: 'SiSwati',
    code2l: 'ss',
    code3l: 'ssw',
  },
  {
    name: 'Swedish',
    native: 'Svenska',
    code2l: 'sv',
    code3l: 'swe',
  },
  {
    name: 'Tamil',
    native: 'தமிழ்',
    code2l: 'ta',
    code3l: 'tam',
  },
  {
    name: 'Telugu',
    native: 'తెలుగు',
    code2l: 'te',
    code3l: 'tel',
  },
  {
    name: 'Tajik',
    native: 'тоҷикӣ, toçikī, تاجیکی‎',
    code2l: 'tg',
    code3l: 'tgk',
  },
  {
    name: 'Thai',
    native: 'ไทย',
    code2l: 'th',
    code3l: 'tha',
  },
  {
    name: 'Tigrinya',
    native: 'ትግርኛ',
    code2l: 'ti',
    code3l: 'tir',
  },
  {
    name: 'Tibetan',
    native: 'བོད་ཡིག',
    code2l: 'bo',
    code3l: 'bod',
  },
  {
    name: 'Turkmen',
    native: 'Türkmen, Түркмен',
    code2l: 'tk',
    code3l: 'tuk',
  },
  {
    name: 'Tagalog',
    native: 'Wikang Tagalog',
    code2l: 'tl',
    code3l: 'tgl',
  },
  {
    name: 'Tswana',
    native: 'Setswana',
    code2l: 'tn',
    code3l: 'tsn',
  },
  {
    name: 'Tonga (Tonga Islands)',
    native: 'Faka Tonga',
    code2l: 'to',
    code3l: 'ton',
  },
  {
    name: 'Turkish',
    native: 'Türkçe',
    code2l: 'tr',
    code3l: 'tur',
  },
  {
    name: 'Tsonga',
    native: 'Xitsonga',
    code2l: 'ts',
    code3l: 'tso',
  },
  {
    name: 'Tatar',
    native: 'татар теле, tatar tele',
    code2l: 'tt',
    code3l: 'tat',
  },
  {
    name: 'Twi',
    native: 'Twi',
    code2l: 'tw',
    code3l: 'twi',
  },
  {
    name: 'Tahitian',
    native: 'Reo Tahiti',
    code2l: 'ty',
    code3l: 'tah',
  },
  {
    name: 'Uighur, Uyghur',
    native: 'ئۇيغۇرچە‎, Uyghurche',
    code2l: 'ug',
    code3l: 'uig',
  },
  {
    name: 'Ukrainian',
    native: 'Українська',
    code2l: 'uk',
    code3l: 'ukr',
  },
  {
    name: 'Urdu',
    native: 'اردو',
    code2l: 'ur',
    code3l: 'urd',
  },
  {
    name: 'Uzbek',
    native: 'Oʻzbek, Ўзбек, أۇزبېك‎',
    code2l: 'uz',
    code3l: 'uzb',
  },
  {
    name: 'Venda',
    native: 'Tshivenḓa',
    code2l: 've',
    code3l: 'ven',
  },
  {
    name: 'Vietnamese',
    native: 'Tiếng Việt',
    code2l: 'vi',
    code3l: 'vie',
  },
  {
    name: 'Volapük',
    native: 'Volapük',
    code2l: 'vo',
    code3l: 'vol',
  },
  {
    name: 'Walloon',
    native: 'Walon',
    code2l: 'wa',
    code3l: 'wln',
  },
  {
    name: 'Welsh',
    native: 'Cymraeg',
    code2l: 'cy',
    code3l: 'cym',
  },
  {
    name: 'Wolof',
    native: 'Wollof',
    code2l: 'wo',
    code3l: 'wol',
  },
  {
    name: 'Western Frisian',
    native: 'Frysk',
    code2l: 'fy',
    code3l: 'fry',
  },
  {
    name: 'Xhosa',
    native: 'isiXhosa',
    code2l: 'xh',
    code3l: 'xho',
  },
  {
    name: 'Yiddish',
    native: 'ייִדיש',
    code2l: 'yi',
    code3l: 'yid',
  },
  {
    name: 'Yoruba',
    native: 'Yorùbá',
    code2l: 'yo',
    code3l: 'yor',
  },
  {
    name: 'Zhuang, Chuang',
    native: 'Saɯ cueŋƅ, Saw cuengh',
    code2l: 'za',
    code3l: 'zha',
  },
  {
    name: 'Zulu',
    native: 'isiZulu',
    code2l: 'zu',
    code3l: 'zul',
  },
];

export default languages;
