const countryValues = [
  {
    name: 'Afghanistan',
    fullName: 'Afghanistan',
    l2: 'AF',
    l3: 'AFG',
    num: 4,
  },
  { name: 'Albania', fullName: 'Albania', l2: 'AL', l3: 'ALB', num: 8 },
  { name: 'Algeria', fullName: 'Algeria', l2: 'DZ', l3: 'DZA', num: 12 },
  {
    name: 'American Samoa',
    fullName: 'American Samoa',
    l2: 'AS',
    l3: 'ASM',
    num: 16,
  },
  { name: 'Andorra', fullName: 'Andorra', l2: 'AD', l3: 'AND', num: 20 },
  { name: 'Angola', fullName: 'Angola', l2: 'AO', l3: 'AGO', num: 24 },
  { name: 'Anguilla', fullName: 'Anguilla', l2: 'AI', l3: 'AIA', num: 660 },
  {
    name: 'Antarctica',
    fullName: 'Antarctica',
    l2: 'AQ',
    l3: 'ATA',
    num: 10,
  },
  {
    name: 'Antigua and Barbuda',
    fullName: 'Antigua and Barbuda',
    l2: 'AG',
    l3: 'ATG',
    num: 28,
  },
  { name: 'Argentina', fullName: 'Argentina', l2: 'AR', l3: 'ARG', num: 32 },
  { name: 'Armenia', fullName: 'Armenia', l2: 'AM', l3: 'ARM', num: 51 },
  { name: 'Aruba', fullName: 'Aruba', l2: 'AW', l3: 'ABW', num: 533 },
  { name: 'Australia', fullName: 'Australia', l2: 'AU', l3: 'AUS', num: 36 },
  { name: 'Austria', fullName: 'Austria', l2: 'AT', l3: 'AUT', num: 40 },
  {
    name: 'Azerbaijan',
    fullName: 'Azerbaijan',
    l2: 'AZ',
    l3: 'AZE',
    num: 31,
  },
  {
    name: 'Bahamas (the)',
    fullName: 'Bahamas (the)',
    l2: 'BS',
    l3: 'BHS',
    num: 44,
  },
  { name: 'Bahrain', fullName: 'Bahrain', l2: 'BH', l3: 'BHR', num: 48 },
  {
    name: 'Bangladesh',
    fullName: 'Bangladesh',
    l2: 'BD',
    l3: 'BGD',
    num: 50,
  },
  { name: 'Barbados', fullName: 'Barbados', l2: 'BB', l3: 'BRB', num: 52 },
  { name: 'Belarus', fullName: 'Belarus', l2: 'BY', l3: 'BLR', num: 112 },
  { name: 'Belgium', fullName: 'Belgium', l2: 'BE', l3: 'BEL', num: 56 },
  { name: 'Belize', fullName: 'Belize', l2: 'BZ', l3: 'BLZ', num: 84 },
  { name: 'Benin', fullName: 'Benin', l2: 'BJ', l3: 'BEN', num: 204 },
  { name: 'Bermuda', fullName: 'Bermuda', l2: 'BM', l3: 'BMU', num: 60 },
  { name: 'Bhutan', fullName: 'Bhutan', l2: 'BT', l3: 'BTN', num: 64 },
  {
    name: 'Bolivia',
    fullName: 'Bolivia (Plurinational State of)',
    l2: 'BO',
    l3: 'BOL',
    num: 68,
  },
  {
    name: 'Bonaire, Sint Eustatius and Saba',
    fullName: 'Bonaire, Sint Eustatius and Saba',
    l2: 'BQ',
    l3: 'BES',
    num: 535,
  },
  {
    name: 'Bosnia and Herzegovina',
    fullName: 'Bosnia and Herzegovina',
    l2: 'BA',
    l3: 'BIH',
    num: 70,
  },
  { name: 'Botswana', fullName: 'Botswana', l2: 'BW', l3: 'BWA', num: 72 },
  {
    name: 'Bouvet Island',
    fullName: 'Bouvet Island',
    l2: 'BV',
    l3: 'BVT',
    num: 74,
  },
  { name: 'Brazil', fullName: 'Brazil', l2: 'BR', l3: 'BRA', num: 76 },
  {
    name: 'British Indian Ocean Territory (the)',
    fullName: 'British Indian Ocean Territory (the)',
    l2: 'IO',
    l3: 'IOT',
    num: 86,
  },
  {
    name: 'Brunei Darussalam',
    fullName: 'Brunei Darussalam',
    l2: 'BN',
    l3: 'BRN',
    num: 96,
  },
  { name: 'Bulgaria', fullName: 'Bulgaria', l2: 'BG', l3: 'BGR', num: 100 },
  {
    name: 'Burkina Faso',
    fullName: 'Burkina Faso',
    l2: 'BF',
    l3: 'BFA',
    num: 854,
  },
  { name: 'Burundi', fullName: 'Burundi', l2: 'BI', l3: 'BDI', num: 108 },
  {
    name: 'Cabo Verde',
    fullName: 'Cabo Verde',
    l2: 'CV',
    l3: 'CPV',
    num: 132,
  },
  { name: 'Cambodia', fullName: 'Cambodia', l2: 'KH', l3: 'KHM', num: 116 },
  { name: 'Cameroon', fullName: 'Cameroon', l2: 'CM', l3: 'CMR', num: 120 },
  { name: 'Canada', fullName: 'Canada', l2: 'CA', l3: 'CAN', num: 124 },
  {
    name: 'Cayman Islands (the)',
    fullName: 'Cayman Islands (the)',
    l2: 'KY',
    l3: 'CYM',
    num: 136,
  },
  {
    name: 'Central African Republic',
    fullName: 'Central African Republic (the)',
    l2: 'CF',
    l3: 'CAF',
    num: 140,
  },
  { name: 'Chad', fullName: 'Chad', l2: 'TD', l3: 'TCD', num: 148 },
  { name: 'Chile', fullName: 'Chile', l2: 'CL', l3: 'CHL', num: 152 },
  { name: 'China', fullName: 'China', l2: 'CN', l3: 'CHN', num: 156 },
  {
    name: 'Christmas Island',
    fullName: 'Christmas Island',
    l2: 'CX',
    l3: 'CXR',
    num: 162,
  },
  {
    name: 'Cocos Islands',
    fullName: 'Cocos (Keeling) Islands (the)',
    l2: 'CC',
    l3: 'CCK',
    num: 166,
  },
  { name: 'Colombia', fullName: 'Colombia', l2: 'CO', l3: 'COL', num: 170 },
  {
    name: 'Comoros',
    fullName: 'Comoros (the)',
    l2: 'KM',
    l3: 'COM',
    num: 174,
  },
  {
    name: 'Congo (DRC)',
    fullName: 'Congo (the Democratic Republic of the)',
    l2: 'CD',
    l3: 'COD',
    num: 180,
  },
  {
    name: 'Congo (Brazaville)',
    fullName: 'Congo (the)',
    l2: 'CG',
    l3: 'COG',
    num: 178,
  },
  {
    name: 'Cook Islands)',
    fullName: 'Cook Islands (the)',
    l2: 'CK',
    l3: 'COK',
    num: 184,
  },
  {
    name: 'Costa Rica',
    fullName: 'Costa Rica',
    l2: 'CR',
    l3: 'CRI',
    num: 188,
  },
  { name: 'Croatia', fullName: 'Croatia', l2: 'HR', l3: 'HRV', num: 191 },
  { name: 'Cuba', fullName: 'Cuba', l2: 'CU', l3: 'CUB', num: 192 },
  { name: 'Curaçao', fullName: 'Curaçao', l2: 'CW', l3: 'CUW', num: 531 },
  { name: 'Cyprus', fullName: 'Cyprus', l2: 'CY', l3: 'CYP', num: 196 },
  { name: 'Czechia', fullName: 'Czechia', l2: 'CZ', l3: 'CZE', num: 203 },
  {
    name: "Côte d'Ivoire",
    fullName: 'Ivory Coast',
    l2: 'CI',
    l3: 'CIV',
    num: 384,
  },
  { name: 'Denmark', fullName: 'Denmark', l2: 'DK', l3: 'DNK', num: 208 },
  { name: 'Djibouti', fullName: 'Djibouti', l2: 'DJ', l3: 'DJI', num: 262 },
  { name: 'Dominica', fullName: 'Dominica', l2: 'DM', l3: 'DMA', num: 212 },
  {
    name: 'Dominican Republic',
    fullName: 'Dominican Republic (the)',
    l2: 'DO',
    l3: 'DOM',
    num: 214,
  },
  { name: 'Ecuador', fullName: 'Ecuador', l2: 'EC', l3: 'ECU', num: 218 },
  { name: 'Egypt', fullName: 'Egypt', l2: 'EG', l3: 'EGY', num: 818 },
  {
    name: 'El Salvador',
    fullName: 'El Salvador',
    l2: 'SV',
    l3: 'SLV',
    num: 222,
  },
  {
    name: 'Equatorial Guinea',
    fullName: 'Equatorial Guinea',
    l2: 'GQ',
    l3: 'GNQ',
    num: 226,
  },
  { name: 'Eritrea', fullName: 'Eritrea', l2: 'ER', l3: 'ERI', num: 232 },
  { name: 'Estonia', fullName: 'Estonia', l2: 'EE', l3: 'EST', num: 233 },
  { name: 'Eswatini', fullName: 'Eswatini', l2: 'SZ', l3: 'SWZ', num: 748 },
  { name: 'Ethiopia', fullName: 'Ethiopia', l2: 'ET', l3: 'ETH', num: 231 },
  {
    name: 'Falkland Islands (the) [Malvinas]',
    fullName: 'Falkland Islands (the) [Malvinas]',
    l2: 'FK',
    l3: 'FLK',
    num: 238,
  },
  {
    name: 'Faroe Islands',
    fullName: 'Faroe Islands (the)',
    l2: 'FO',
    l3: 'FRO',
    num: 234,
  },
  { name: 'Fiji', fullName: 'Fiji', l2: 'FJ', l3: 'FJI', num: 242 },
  { name: 'Finland', fullName: 'Finland', l2: 'FI', l3: 'FIN', num: 246 },
  { name: 'France', fullName: 'France', l2: 'FR', l3: 'FRA', num: 250 },
  {
    name: 'French Guiana',
    fullName: 'French Guiana',
    l2: 'GF',
    l3: 'GUF',
    num: 254,
  },
  {
    name: 'French Polynesia',
    fullName: 'French Polynesia',
    l2: 'PF',
    l3: 'PYF',
    num: 258,
  },
  {
    name: 'French Southern Territories',
    fullName: 'French Southern Territories (the)',
    l2: 'TF',
    l3: 'ATF',
    num: 260,
  },
  { name: 'Gabon', fullName: 'Gabon', l2: 'GA', l3: 'GAB', num: 266 },
  {
    name: 'Gambia',
    fullName: 'Gambia (the)',
    l2: 'GM',
    l3: 'GMB',
    num: 270,
  },
  { name: 'Georgia', fullName: 'Georgia', l2: 'GE', l3: 'GEO', num: 268 },
  { name: 'Germany', fullName: 'Germany', l2: 'DE', l3: 'DEU', num: 276 },
  { name: 'Ghana', fullName: 'Ghana', l2: 'GH', l3: 'GHA', num: 288 },
  { name: 'Gibraltar', fullName: 'Gibraltar', l2: 'GI', l3: 'GIB', num: 292 },
  { name: 'Greece', fullName: 'Greece', l2: 'GR', l3: 'GRC', num: 300 },
  { name: 'Greenland', fullName: 'Greenland', l2: 'GL', l3: 'GRL', num: 304 },
  { name: 'Grenada', fullName: 'Grenada', l2: 'GD', l3: 'GRD', num: 308 },
  {
    name: 'Guadeloupe',
    fullName: 'Guadeloupe',
    l2: 'GP',
    l3: 'GLP',
    num: 312,
  },
  { name: 'Guam', fullName: 'Guam', l2: 'GU', l3: 'GUM', num: 316 },
  { name: 'Guatemala', fullName: 'Guatemala', l2: 'GT', l3: 'GTM', num: 320 },
  { name: 'Guernsey', fullName: 'Guernsey', l2: 'GG', l3: 'GGY', num: 831 },
  { name: 'Guinea', fullName: 'Guinea', l2: 'GN', l3: 'GIN', num: 324 },
  {
    name: 'Guinea-Bissau',
    fullName: 'Guinea-Bissau',
    l2: 'GW',
    l3: 'GNB',
    num: 624,
  },
  { name: 'Guyana', fullName: 'Guyana', l2: 'GY', l3: 'GUY', num: 328 },
  { name: 'Haiti', fullName: 'Haiti', l2: 'HT', l3: 'HTI', num: 332 },
  {
    name: 'Heard Island and McDonald Islands',
    fullName: 'Heard Island and McDonald Islands',
    l2: 'HM',
    l3: 'HMD',
    num: 334,
  },
  {
    name: 'Holy See',
    fullName: 'Holy See (the)',
    l2: 'VA',
    l3: 'VAT',
    num: 336,
  },
  { name: 'Honduras', fullName: 'Honduras', l2: 'HN', l3: 'HND', num: 340 },
  { name: 'Hong Kong', fullName: 'Hong Kong', l2: 'HK', l3: 'HKG', num: 344 },
  { name: 'Hungary', fullName: 'Hungary', l2: 'HU', l3: 'HUN', num: 348 },
  { name: 'Iceland', fullName: 'Iceland', l2: 'IS', l3: 'ISL', num: 352 },
  { name: 'India', fullName: 'India', l2: 'IN', l3: 'IND', num: 356 },
  { name: 'Indonesia', fullName: 'Indonesia', l2: 'ID', l3: 'IDN', num: 360 },
  {
    name: 'Iran',
    fullName: 'Iran (Islamic Republic of)',
    l2: 'IR',
    l3: 'IRN',
    num: 364,
  },
  { name: 'Iraq', fullName: 'Iraq', l2: 'IQ', l3: 'IRQ', num: 368 },
  { name: 'Ireland', fullName: 'Ireland', l2: 'IE', l3: 'IRL', num: 372 },
  {
    name: 'Isle of Man',
    fullName: 'Isle of Man',
    l2: 'IM',
    l3: 'IMN',
    num: 833,
  },
  { name: 'Israel', fullName: 'Israel', l2: 'IL', l3: 'ISR', num: 376 },
  { name: 'Italy', fullName: 'Italy', l2: 'IT', l3: 'ITA', num: 380 },
  { name: 'Jamaica', fullName: 'Jamaica', l2: 'JM', l3: 'JAM', num: 388 },
  { name: 'Japan', fullName: 'Japan', l2: 'JP', l3: 'JPN', num: 392 },
  { name: 'Jersey', fullName: 'Jersey', l2: 'JE', l3: 'JEY', num: 832 },
  { name: 'Jordan', fullName: 'Jordan', l2: 'JO', l3: 'JOR', num: 400 },
  {
    name: 'Kazakhstan',
    fullName: 'Kazakhstan',
    l2: 'KZ',
    l3: 'KAZ',
    num: 398,
  },
  { name: 'Kenya', fullName: 'Kenya', l2: 'KE', l3: 'KEN', num: 404 },
  { name: 'Kiribati', fullName: 'Kiribati', l2: 'KI', l3: 'KIR', num: 296 },
  {
    name: "Korea (the Democratic People's Republic of)",
    l2: 'KP',
    l3: 'PRK',
    num: 408,
  },
  {
    name: 'Korea (the Republic of)',
    fullName: 'Korea (the Republic of)',
    l2: 'KR',
    l3: 'KOR',
    num: 410,
  },
  { name: 'Kuwait', fullName: 'Kuwait', l2: 'KW', l3: 'KWT', num: 414 },
  {
    name: 'Kyrgyzstan',
    fullName: 'Kyrgyzstan',
    l2: 'KG',
    l3: 'KGZ',
    num: 417,
  },
  {
    name: "Lao People's Democratic Republic (the)",
    l2: 'LA',
    l3: 'LAO',
    num: 418,
  },
  { name: 'Latvia', fullName: 'Latvia', l2: 'LV', l3: 'LVA', num: 428 },
  { name: 'Lebanon', fullName: 'Lebanon', l2: 'LB', l3: 'LBN', num: 422 },
  { name: 'Lesotho', fullName: 'Lesotho', l2: 'LS', l3: 'LSO', num: 426 },
  { name: 'Liberia', fullName: 'Liberia', l2: 'LR', l3: 'LBR', num: 430 },
  { name: 'Libya', fullName: 'Libya', l2: 'LY', l3: 'LBY', num: 434 },
  {
    name: 'Liechtenstein',
    fullName: 'Liechtenstein',
    l2: 'LI',
    l3: 'LIE',
    num: 438,
  },
  { name: 'Lithuania', fullName: 'Lithuania', l2: 'LT', l3: 'LTU', num: 440 },
  {
    name: 'Luxembourg',
    fullName: 'Luxembourg',
    l2: 'LU',
    l3: 'LUX',
    num: 442,
  },
  { name: 'Macao', fullName: 'Macao', l2: 'MO', l3: 'MAC', num: 446 },
  {
    name: 'Madagascar',
    fullName: 'Madagascar',
    l2: 'MG',
    l3: 'MDG',
    num: 450,
  },
  { name: 'Malawi', fullName: 'Malawi', l2: 'MW', l3: 'MWI', num: 454 },
  { name: 'Malaysia', fullName: 'Malaysia', l2: 'MY', l3: 'MYS', num: 458 },
  { name: 'Maldives', fullName: 'Maldives', l2: 'MV', l3: 'MDV', num: 462 },
  { name: 'Mali', fullName: 'Mali', l2: 'ML', l3: 'MLI', num: 466 },
  { name: 'Malta', fullName: 'Malta', l2: 'MT', l3: 'MLT', num: 470 },
  {
    name: 'Marshall Islands (the)',
    fullName: 'Marshall Islands (the)',
    l2: 'MH',
    l3: 'MHL',
    num: 584,
  },
  {
    name: 'Martinique',
    fullName: 'Martinique',
    l2: 'MQ',
    l3: 'MTQ',
    num: 474,
  },
  {
    name: 'Mauritania',
    fullName: 'Mauritania',
    l2: 'MR',
    l3: 'MRT',
    num: 478,
  },
  { name: 'Mauritius', fullName: 'Mauritius', l2: 'MU', l3: 'MUS', num: 480 },
  { name: 'Mayotte', fullName: 'Mayotte', l2: 'YT', l3: 'MYT', num: 175 },
  { name: 'Mexico', fullName: 'Mexico', l2: 'MX', l3: 'MEX', num: 484 },
  {
    name: 'Micronesia',
    fullName: 'Micronesia (Federated States of)',
    l2: 'FM',
    l3: 'FSM',
    num: 583,
  },
  {
    name: 'Moldova',
    fullName: 'Moldova (the Republic of)',
    l2: 'MD',
    l3: 'MDA',
    num: 498,
  },
  { name: 'Monaco', fullName: 'Monaco', l2: 'MC', l3: 'MCO', num: 492 },
  { name: 'Mongolia', fullName: 'Mongolia', l2: 'MN', l3: 'MNG', num: 496 },
  {
    name: 'Montenegro',
    fullName: 'Montenegro',
    l2: 'ME',
    l3: 'MNE',
    num: 499,
  },
  {
    name: 'Montserrat',
    fullName: 'Montserrat',
    l2: 'MS',
    l3: 'MSR',
    num: 500,
  },
  { name: 'Morocco', fullName: 'Morocco', l2: 'MA', l3: 'MAR', num: 504 },
  {
    name: 'Mozambique',
    fullName: 'Mozambique',
    l2: 'MZ',
    l3: 'MOZ',
    num: 508,
  },
  { name: 'Myanmar', fullName: 'Myanmar', l2: 'MM', l3: 'MMR', num: 104 },
  { name: 'Namibia', fullName: 'Namibia', l2: 'NA', l3: 'NAM', num: 516 },
  { name: 'Nauru', fullName: 'Nauru', l2: 'NR', l3: 'NRU', num: 520 },
  { name: 'Nepal', fullName: 'Nepal', l2: 'NP', l3: 'NPL', num: 524 },
  {
    name: 'Netherlands',
    fullName: 'Netherlands (the)',
    l2: 'NL',
    l3: 'NLD',
    num: 528,
  },
  {
    name: 'New Caledonia',
    fullName: 'New Caledonia',
    l2: 'NC',
    l3: 'NCL',
    num: 540,
  },
  {
    name: 'New Zealand',
    fullName: 'New Zealand',
    l2: 'NZ',
    l3: 'NZL',
    num: 554,
  },
  { name: 'Nicaragua', fullName: 'Nicaragua', l2: 'NI', l3: 'NIC', num: 558 },
  {
    name: 'Niger (the)',
    fullName: 'Niger (the)',
    l2: 'NE',
    l3: 'NER',
    num: 562,
  },
  { name: 'Nigeria', fullName: 'Nigeria', l2: 'NG', l3: 'NGA', num: 566 },
  { name: 'Niue', fullName: 'Niue', l2: 'NU', l3: 'NIU', num: 570 },
  {
    name: 'Norfolk Island',
    fullName: 'Norfolk Island',
    l2: 'NF',
    l3: 'NFK',
    num: 574,
  },
  {
    name: 'Northern Mariana Islands',
    fullName: 'Northern Mariana Islands (the)',
    l2: 'MP',
    l3: 'MNP',
    num: 580,
  },
  { name: 'Norway', fullName: 'Norway', l2: 'NO', l3: 'NOR', num: 578 },
  { name: 'Oman', fullName: 'Oman', l2: 'OM', l3: 'OMN', num: 512 },
  { name: 'Pakistan', fullName: 'Pakistan', l2: 'PK', l3: 'PAK', num: 586 },
  { name: 'Palau', fullName: 'Palau', l2: 'PW', l3: 'PLW', num: 585 },
  {
    name: 'Palestine',
    fullName: 'Palestine, State of',
    l2: 'PS',
    l3: 'PSE',
    num: 275,
  },
  { name: 'Panama', fullName: 'Panama', l2: 'PA', l3: 'PAN', num: 591 },
  {
    name: 'Papua New Guinea',
    fullName: 'Papua New Guinea',
    l2: 'PG',
    l3: 'PNG',
    num: 598,
  },
  { name: 'Paraguay', fullName: 'Paraguay', l2: 'PY', l3: 'PRY', num: 600 },
  { name: 'Peru', fullName: 'Peru', l2: 'PE', l3: 'PER', num: 604 },
  {
    name: 'Philippines',
    fullName: 'Philippines (the)',
    l2: 'PH',
    l3: 'PHL',
    num: 608,
  },
  { name: 'Pitcairn', fullName: 'Pitcairn', l2: 'PN', l3: 'PCN', num: 612 },
  { name: 'Poland', fullName: 'Poland', l2: 'PL', l3: 'POL', num: 616 },
  { name: 'Portugal', fullName: 'Portugal', l2: 'PT', l3: 'PRT', num: 620 },
  {
    name: 'Puerto Rico',
    fullName: 'Puerto Rico',
    l2: 'PR',
    l3: 'PRI',
    num: 630,
  },
  { name: 'Qatar', fullName: 'Qatar', l2: 'QA', l3: 'QAT', num: 634 },
  {
    name: 'North Macedonia',
    fullName: 'Republic of North Macedonia',
    l2: 'MK',
    l3: 'MKD',
    num: 807,
  },
  { name: 'Romania', fullName: 'Romania', l2: 'RO', l3: 'ROU', num: 642 },
  {
    name: 'Russia',
    fullName: 'Russian Federation (the)',
    l2: 'RU',
    l3: 'RUS',
    num: 643,
  },
  { name: 'Rwanda', fullName: 'Rwanda', l2: 'RW', l3: 'RWA', num: 646 },
  { name: 'Réunion', fullName: 'Réunion', l2: 'RE', l3: 'REU', num: 638 },
  {
    name: 'Saint Barthélemy',
    fullName: 'Saint Barthélemy',
    l2: 'BL',
    l3: 'BLM',
    num: 652,
  },
  {
    name: 'Saint Helena, Ascension and Tristan da Cunha',
    fullName: 'Saint Helena, Ascension and Tristan da Cunha',
    l2: 'SH',
    l3: 'SHN',
    num: 654,
  },
  {
    name: 'Saint Kitts and Nevis',
    fullName: 'Saint Kitts and Nevis',
    l2: 'KN',
    l3: 'KNA',
    num: 659,
  },
  {
    name: 'Saint Lucia',
    fullName: 'Saint Lucia',
    l2: 'LC',
    l3: 'LCA',
    num: 662,
  },
  {
    name: 'Saint Martin (French)',
    fullName: 'Saint Martin (French part)',
    l2: 'MF',
    l3: 'MAF',
    num: 663,
  },
  {
    name: 'Saint Pierre and Miquelon',
    fullName: 'Saint Pierre and Miquelon',
    l2: 'PM',
    l3: 'SPM',
    num: 666,
  },
  {
    name: 'Saint Vincent and the Grenadines',
    fullName: 'Saint Vincent and the Grenadines',
    l2: 'VC',
    l3: 'VCT',
    num: 670,
  },
  { name: 'Samoa', fullName: 'Samoa', l2: 'WS', l3: 'WSM', num: 882 },
  {
    name: 'San Marino',
    fullName: 'San Marino',
    l2: 'SM',
    l3: 'SMR',
    num: 674,
  },
  {
    name: 'Sao Tome and Principe',
    fullName: 'Sao Tome and Principe',
    l2: 'ST',
    l3: 'STP',
    num: 678,
  },
  {
    name: 'Saudi Arabia',
    fullName: 'Saudi Arabia',
    l2: 'SA',
    l3: 'SAU',
    num: 682,
  },
  { name: 'Senegal', fullName: 'Senegal', l2: 'SN', l3: 'SEN', num: 686 },
  { name: 'Serbia', fullName: 'Serbia', l2: 'RS', l3: 'SRB', num: 688 },
  {
    name: 'Seychelles',
    fullName: 'Seychelles',
    l2: 'SC',
    l3: 'SYC',
    num: 690,
  },
  {
    name: 'Sierra Leone',
    fullName: 'Sierra Leone',
    l2: 'SL',
    l3: 'SLE',
    num: 694,
  },
  { name: 'Singapore', fullName: 'Singapore', l2: 'SG', l3: 'SGP', num: 702 },
  {
    name: 'Sint Maarten (Dutch)',
    fullName: 'Sint Maarten (Dutch part)',
    l2: 'SX',
    l3: 'SXM',
    num: 534,
  },
  { name: 'Slovakia', fullName: 'Slovakia', l2: 'SK', l3: 'SVK', num: 703 },
  { name: 'Slovenia', fullName: 'Slovenia', l2: 'SI', l3: 'SVN', num: 705 },
  {
    name: 'Solomon Islands',
    fullName: 'Solomon Islands',
    l2: 'SB',
    l3: 'SLB',
    num: 90,
  },
  { name: 'Somalia', fullName: 'Somalia', l2: 'SO', l3: 'SOM', num: 706 },
  {
    name: 'South Africa',
    fullName: 'South Africa',
    l2: 'ZA',
    l3: 'ZAF',
    num: 710,
  },
  {
    name: 'South Georgia and South Sandwich Islands',
    fullName: 'South Georgia and the South Sandwich Islands',
    l2: 'GS',
    l3: 'SGS',
    num: 239,
  },
  {
    name: 'South Sudan',
    fullName: 'South Sudan',
    l2: 'SS',
    l3: 'SSD',
    num: 728,
  },
  { name: 'Spain', fullName: 'Spain', l2: 'ES', l3: 'ESP', num: 724 },
  { name: 'Sri Lanka', fullName: 'Sri Lanka', l2: 'LK', l3: 'LKA', num: 144 },
  {
    name: 'Sudan (the)',
    fullName: 'Sudan (the)',
    l2: 'SD',
    l3: 'SDN',
    num: 729,
  },
  { name: 'Suriname', fullName: 'Suriname', l2: 'SR', l3: 'SUR', num: 740 },
  {
    name: 'Svalbard and Jan Mayen',
    fullName: 'Svalbard and Jan Mayen',
    l2: 'SJ',
    l3: 'SJM',
    num: 744,
  },
  { name: 'Sweden', fullName: 'Sweden', l2: 'SE', l3: 'SWE', num: 752 },
  {
    name: 'Switzerland',
    fullName: 'Switzerland',
    l2: 'CH',
    l3: 'CHE',
    num: 756,
  },
  {
    name: 'Syrian Arab Republic',
    fullName: 'Syrian Arab Republic',
    l2: 'SY',
    l3: 'SYR',
    num: 760,
  },
  {
    name: 'Taiwan (Province of China)',
    fullName: 'Taiwan (Province of China)',
    l2: 'TW',
    l3: 'TWN',
    num: 158,
  },
  {
    name: 'Tajikistan',
    fullName: 'Tajikistan',
    l2: 'TJ',
    l3: 'TJK',
    num: 762,
  },
  {
    name: 'Tanzania',
    fullName: 'Tanzania, United Republic of',
    l2: 'TZ',
    l3: 'TZA',
    num: 834,
  },
  { name: 'Thailand', fullName: 'Thailand', l2: 'TH', l3: 'THA', num: 764 },
  {
    name: 'Timor-Leste',
    fullName: 'Timor-Leste',
    l2: 'TL',
    l3: 'TLS',
    num: 626,
  },
  { name: 'Togo', fullName: 'Togo', l2: 'TG', l3: 'TGO', num: 768 },
  { name: 'Tokelau', fullName: 'Tokelau', l2: 'TK', l3: 'TKL', num: 772 },
  { name: 'Tonga', fullName: 'Tonga', l2: 'TO', l3: 'TON', num: 776 },
  {
    name: 'Trinidad and Tobago',
    fullName: 'Trinidad and Tobago',
    l2: 'TT',
    l3: 'TTO',
    num: 780,
  },
  { name: 'Tunisia', fullName: 'Tunisia', l2: 'TN', l3: 'TUN', num: 788 },
  { name: 'Turkey', fullName: 'Turkey', l2: 'TR', l3: 'TUR', num: 792 },
  {
    name: 'Turkmenistan',
    fullName: 'Turkmenistan',
    l2: 'TM',
    l3: 'TKM',
    num: 795,
  },
  {
    name: 'Turks and Caicos Islands (the)',
    fullName: 'Turks and Caicos Islands (the)',
    l2: 'TC',
    l3: 'TCA',
    num: 796,
  },
  { name: 'Tuvalu', fullName: 'Tuvalu', l2: 'TV', l3: 'TUV', num: 798 },
  { name: 'Uganda', fullName: 'Uganda', l2: 'UG', l3: 'UGA', num: 800 },
  { name: 'Ukraine', fullName: 'Ukraine', l2: 'UA', l3: 'UKR', num: 804 },
  {
    name: 'United Arab Emirates (the)',
    fullName: 'United Arab Emirates (the)',
    l2: 'AE',
    l3: 'ARE',
    num: 784,
  },
  {
    name: 'United Kingdom',
    fullName: 'United Kingdom of Great Britain and Northern Ireland (the)',
    l2: 'GB',
    l3: 'GBR',
    num: 826,
  },
  {
    name: 'US Minor Outlying Islands',
    fullName: 'United States Minor Outlying Islands (the)',
    l2: 'UM',
    l3: 'UMI',
    num: 581,
  },
  {
    name: 'USA',
    fullName: 'United States of America (the)',
    l2: 'US',
    l3: 'USA',
    num: 840,
  },
  { name: 'Uruguay', fullName: 'Uruguay', l2: 'UY', l3: 'URY', num: 858 },
  {
    name: 'Uzbekistan',
    fullName: 'Uzbekistan',
    l2: 'UZ',
    l3: 'UZB',
    num: 860,
  },
  { name: 'Vanuatu', fullName: 'Vanuatu', l2: 'VU', l3: 'VUT', num: 548 },
  {
    name: 'Venezuela',
    fullName: 'Venezuela (Bolivarian Republic of)',
    l2: 'VE',
    l3: 'VEN',
    num: 862,
  },
  { name: 'Viet Nam', fullName: 'Viet Nam', l2: 'VN', l3: 'VNM', num: 704 },
  {
    name: 'Virgin Islands (UK)',
    fullName: 'Virgin Islands (British)',
    l2: 'VG',
    l3: 'VGB',
    num: 92,
  },
  {
    name: 'Virgin Islands (US)',
    fullName: 'Virgin Islands (U.S.)',
    l2: 'VI',
    l3: 'VIR',
    num: 850,
  },
  {
    name: 'Wallis and Futuna',
    fullName: 'Wallis and Futuna',
    l2: 'WF',
    l3: 'WLF',
    num: 876,
  },
  {
    name: 'Western Sahara',
    fullName: 'Western Sahara',
    l2: 'EH',
    l3: 'ESH',
    num: 732,
  },
  { name: 'Yemen', fullName: 'Yemen', l2: 'YE', l3: 'YEM', num: 887 },
  { name: 'Zambia', fullName: 'Zambia', l2: 'ZM', l3: 'ZMB', num: 894 },
  { name: 'Zimbabwe', fullName: 'Zimbabwe', l2: 'ZW', l3: 'ZWE', num: 716 },
  {
    name: 'Åland Islands',
    fullName: 'Åland Islands',
    l2: 'AX',
    l3: 'ALA',
    num: 248,
  },
];

export default countryValues;
