export default [
  { key: 'fortune', name: 'Fortune' },
  { key: 'spirit', name: 'Spirit' },
  { key: 'eros', name: 'Eros' },
  { key: 'necessity', name: 'Necessity' },
  { key: 'courage', name: 'Courage' },
  { key: 'victory', name: 'Victory' },
  { key: 'nemesis', name: 'Nemesis' },
  { key: 'sexFemale', name: 'Sex (Female)' },
  { key: 'sexMale', name: 'Sex (Male)' },
  { key: 'marriage', name: 'Marriage' },
  { key: 'children', name: 'Children' },
  { key: 'basis', name: 'Basis' },
  { key: 'exaltation', name: 'Exaltation' },
];
